name: jtiledownloader
version: 0.6.1-1.3
summary: Download OSM maps
description: Download maps from OpenStreetMap for offline use
grade: stable
confinement: strict

apps:
    jtiledownloader:
      command: wrapper
      plugs: [home, x11, network, network-bind]

parts:
  tiledownload:
    source: ./
    plugin: make
    build-packages:
      - wget
      - unzip
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
    stage-packages:
      - gtk2-engines-murrine
      - hicolor-icon-theme
      - openjdk-8-jdk
