#!/bin/sh

if [ "$SNAP_ARCH" = "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

# java
export JAVA_HOME=$SNAP/usr/lib/jvm/java-1.8.0-openjdk-$SNAP_ARCH
export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH

# fonts
export XDG_DATA_HOME=$SNAP/usr/share
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf

# theme (currently unused)
export GTK2_RC_FILES=$SNAP/gtkrc

export GTK_PATH=$SNAP/usr/lib/$ARCH/gtk-2.0

# gdk pixbuf
export GDK_PIXBUF_MODULE_FILE=$SNAP_USER_DATA/.gdk-pixbuf-loaders.cache
export GDK_PIXBUF_MODULEDIR=$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/2.10.0/loaders
$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $GDK_PIXBUF_MODULE_FILE

# default config
[ -e "$SNAP_USER_DATA/appConfig.xml" ] || cp $SNAP/appConfig.xml $SNAP_USER_DATA/appConfig.xml

cd $SNAP_USER_DATA

$JAVA_HOME/jre/bin/java -jar $SNAP/jTileDownloader-0-6-1.jar
